static const AVInputFormat * const demuxer_list[] = {
    &ff_aac_demuxer,
    &ff_avi_demuxer,
    &ff_dnxhd_demuxer,
    &ff_flac_demuxer,
    &ff_flv_demuxer,
    &ff_gif_demuxer,
    &ff_h261_demuxer,
    &ff_h263_demuxer,
    &ff_h264_demuxer,
    &ff_image2_demuxer,
    &ff_matroska_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_ogg_demuxer,
    &ff_srt_demuxer,
    &ff_wav_demuxer,
    &ff_webvtt_demuxer,
    NULL };
